git clone https://github.com/ryb73/dealers-choice-card-pack.git card-pack
git clone https://github.com/ryb73/dealers-choice-card-interfaces.git card-interfaces
git clone https://github.com/ryb73/dealers-choice-engine.git engine
git clone https://github.com/ryb73/dealers-choice-test.git test
git clone https://github.com/ryb73/dealers-choice-server.git server
git clone https://github.com/ryb73/dealers-choice-game-factory.git game-factory
git clone https://github.com/ryb73/dealers-choice-game-states.git game-states
git clone https://github.com/ryb73/dealers-choice-front-end.git front-end
git clone https://github.com/ryb73/dealers-choice-game-ui.git game-ui
git clone https://github.com/ryb73/dealers-choice-constants.git constants
