---
- hosts: all
  tasks:
    - name: Update apt-cache
      apt: update_cache=yes
      become: yes

    - include: zsh.yml
    - include: node.yml
    - include: dc-server.yml
    - include: dc-front-end.yml